name: TriLobby
main: net.trilleo.mc.plugins.trilobby.Main
version: ${projectVersion}
api-version: 1.21
authors: [ Trilleo ]

commands:
  trilobby:
    description: Main command for the TriLobby plugin
    usage: /trilobby <subcommand> [args]
    aliases:
      - tl